services:
  - type: web
    name: sigint-mx
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
